//
//  MimeType.swift
//  
//
//  Created by David Cortes on 24/2/22.
//

import Foundation

public enum MimeType: String {
    case aac = "audio/aac"
    case abw = "application/x-abiword"
    case avi = "video/x-msvideo"
    case azw = "application/vnd.amazon.ebook"
    case bz = "application/x-bzip"
    case bz2 = "application/x-bzip2"
    case csh = "application/x-csh"
    case css = "text/css"
    case csv = "text/csv"
    case doc = "application/msword"
    case epub = "application/epub+zip"
    case gif = "image/gif"
    case html = "text/html"
    case ico = "image/x-icon"
    case ics = "text/calendar"
    case jar = "application/java-archive"
    case jpeg = "image/jpeg"
    case js = "application/javascript"
    case json = "application/json"
    case midi = "audio/midi"
    case mpeg = "video/mpeg"
    case mpkg = "application/vnd.apple.installer+xml"
    case octet = "application/octet-stream"
    case odp = "application/vnd.oasis.opendocument.presentation"
    case ods = "application/vnd.oasis.opendocument.spreadsheet"
    case odt = "application/vnd.oasis.opendocument.text"
    case oga = "audio/ogg"
    case ogv = "video/ogg"
    case ogx = "application/ogg"
    case pdf = "application/pdf"
    case png = "image/png"
    case ppt = "application/vnd.ms-powerpoint"
    case rar = "application/x-rar-compressed"
    case rtf = "application/rtf"
    case sh = "application/x-sh"
    case svg = "image/svg+xml"
    case swf = "application/x-shockwave-flash"
    case tar = "application/x-tar"
    case text = "text/plain"
    case tiff = "image/tiff"
    case ttf = "font/ttf"
    case vsd = "application/vnd.visio"
    case wav = "audio/x-wav"
    case weba = "audio/webm"
    case webm = "video/webm"
    case webp = "image/webp"
    case woff = "font/woff"
    case woff2 = "font/woff2"
    case xhtml = "application/xhtml+xml"
    case xls = "application/vnd.ms-excel"
    case xml = "application/xml"
    case xul = "application/vnd.mozilla.xul+xml"
    case zip = "application/zip"
}
